# Generated by Django 3.1.7 on 2021-04-19 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Füge einen Titel für die Emission hinzu', max_length=200)),
                ('beschreibung', models.TextField(help_text='Füge eine Beschreibung der Emission hinzu', max_length=1000)),
                ('wert', models.IntegerField(help_text='C02 Menge in Gramm', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Frage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Füge eine prägnante Frage hinzu (z.B.: Wie viele Flyer wurden gedruckt?)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Emissions',
        ),
        migrations.AddField(
            model_name='frage',
            name='kategorie',
            field=models.ForeignKey(help_text='Wähle eine Kategorie für die Frage', null=True, on_delete=django.db.models.deletion.SET_NULL, to='list.kategorie'),
        ),
        migrations.AddField(
            model_name='emission',
            name='kategorie',
            field=models.ForeignKey(help_text='Wähle eine Kategorie für die Emission', null=True, on_delete=django.db.models.deletion.SET_NULL, to='list.kategorie'),
        ),
    ]
