# Generated by Django 3.1.7 on 2021-04-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20210419_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emission',
            options={'verbose_name_plural': 'Emissionen'},
        ),
        migrations.AlterModelOptions(
            name='frage',
            options={'verbose_name_plural': 'Fragen'},
        ),
        migrations.AlterModelOptions(
            name='kategorie',
            options={'verbose_name_plural': 'Kategorien'},
        ),
    ]
