# Generated by Django 3.1.7 on 2021-04-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20210424_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veranstaltungstyp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Füge einen Titel für die Art der Veranstaltung hinzu', max_length=200)),
                ('frage', models.ManyToManyField(help_text='Wähle Fragen für den Veranstaltungstyp aus', to='list.Frage')),
            ],
            options={
                'verbose_name_plural': 'Veranstaltungstypen',
            },
        ),
    ]
