# Generated by Django 3.1.7 on 2021-04-19 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('shorty', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('question_text', models.CharField(max_length=200)),
                ('category', models.ForeignKey(default='Unsortiert', on_delete=django.db.models.deletion.CASCADE, to='rechner.category', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('emission', models.DecimalField(decimal_places=5, max_digits=10)),
                ('source', models.ManyToManyField(to='rechner.Source')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultAmounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True, verbose_name='Default Value')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechner.question')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechner.eventtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.DecimalField(decimal_places=5, max_digits=10)),
                ('emission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechner.emission')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechner.question')),
            ],
        ),
    ]
