# Generated by Django 3.1.7 on 2022-09-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='emissions',
            field=models.ManyToManyField(to='rechner.Emission'),
        ),
        migrations.AddField(
            model_name='question',
            name='info_text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='question',
            name='multiply_by_ppl',
            field=models.BooleanField(default=False),
        ),
    ]
