# Generated by Django 3.1.7 on 2021-04-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechner', '0002_auto_20210402_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtemplate',
            name='shorty',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
