# Generated by Django 3.1.7 on 2021-03-11 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rechner', '0003_auto_20210311_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(default='Unsortiert', on_delete=django.db.models.deletion.CASCADE, to='rechner.category', to_field='name'),
        ),
    ]
