# Generated by Django 3.1.7 on 2021-03-11 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rechner', '0004_auto_20210311_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
    ]
