# Generated by Django 3.1.7 on 2021-03-11 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rechner', '0005_remove_question_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
