# Generated by Django 3.1.7 on 2021-03-11 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rechner', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(default='Unsortiert', on_delete=django.db.models.deletion.CASCADE, to='rechner.category', to_field='name'),
        ),
    ]
