# Generated by Django 3.1.7 on 2021-03-13 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rechner', '0008_question_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='calc_co2',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('questions', models.ManyToManyField(to='rechner.Question')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultAmounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechner.question')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechner.eventtemplate')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='products',
            field=models.ManyToManyField(to='rechner.Product'),
        ),
    ]
