# Generated by Django 3.1.7 on 2021-04-01 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rechner', '0009_auto_20210313_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_co2', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('emission', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventtemplate',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='calc_co2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='products',
        ),
        migrations.AddField(
            model_name='defaultamounts',
            name='value',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='emission',
            name='source',
            field=models.ManyToManyField(to='rechner.Source'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechner.emission'),
        ),
        migrations.AddField(
            model_name='calculation',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechner.question'),
        ),
    ]
