# Generated by Django 3.1.7 on 2021-04-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechner', '0010_auto_20210401_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculation',
            old_name='product',
            new_name='emission',
        ),
        migrations.RenameField(
            model_name='calculation',
            old_name='calc_co2',
            new_name='ratio',
        ),
        migrations.AlterField(
            model_name='defaultamounts',
            name='value',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Default Value'),
        ),
    ]
